spring:
 datasource:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:shopapp}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASSWORD:password}
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   jdbc:
    time_zone: Asia/Ho_Chi_Minh
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
#validate hinh anh
servlet:
 multipart:
   max-file-size: 10MB
   max-request-size: 10MB

#bien final
api:
 prefix: api/v1





 logging.level.org.springframework.security: DEBUG
